#!/bin/bash
sudo apt-get update
sudo apt-get install cmake libssl-dev libcrypto++-dev libcurl4-openssl-dev
#can replace "libcurl4-openssl-dev" with "libcurl4-nss-dev" or "libcurl4-gnutls-dev"
sudo apt-get install gcc #required for fasttree compile

sudo apt-get install default-jdk #required for java compiling
#sudo apt-get install openjdk-7-jdk