#!/bin/bash
#from http://www.microbesonline.org/fasttree/ 
#version 2.1.8

cd FastTree

#below useful for 32-bit compilation

gcc -O3 -finline-functions -funroll-loops -Wall -o FastTree FastTree.c -lm
#if above line fails try
#gcc -DNO_SSE -O3 -finline-functions -funroll-loops -Wall -o FastTree FastTree.c -lm

#MPversion
gcc -DOPENMP -fopenmp -O3 -finline-functions -funroll-loops -Wall -o FastTreeMP FastTree.c -lm