#!/bin/bash
#from http://www.microbesonline.org/fasttree/ 
#version 2.1.8

#try provided binaries first:  type in the terminal '<full directory>/FastTree' or '<full directory>/FastTreeMP' -> if the response is multiple lines i.e. shows how to use the program, then the file is compatible with the system
#e.g. if NREVanalysis is located in Documents folder then open a terminal and type '~Documents/NREVanalysis/FastTree/FastTreeMP
#the first output line should be 'Usage for FastTree version...' etc.
#if there is an error such as cannot find the command or must install the program, compile by running ONE of the commands below in the terminal (as well as 'cd FastTree') OR running this file

cd FastTree

#below useful for 32-bit compilation

gcc -O3 -finline-functions -funroll-loops -Wall -o FastTree FastTree.c -lm
#if above line fails try
#gcc -DNO_SSE -O3 -finline-functions -funroll-loops -Wall -o FastTree FastTree.c -lm

#MPversion
gcc -DOPENMP -fopenmp -O3 -finline-functions -funroll-loops -Wall -o FastTreeMP FastTree.c -lm